### ISSUE TITLE
Weekly Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#10]
## Value Proposition

As a User
I need a Weekly Log
to be able to work with it.

## Description

![Weekly Log](https://user-images.githubusercontent.com/106076920/179471782-cc7cb4de-161d-4a8c-bc2e-2e37f80ad12c.png)

Scribble / design or text

## Acceptance Criteria
- [ ] The heading states "Weekly."
- [ ] The body contains all seven days, Monday through Sunday.
- [ ] You may modify each day by clicking on it.
- [ ] A weekly objective will be added if necessary.
- [ ] There are three boxes beneath that are buttons.
- [ ] The three buttons are labeled "previous week," "next week," and "current month."
- [ ] In the footer, there is also a navbar. 

## Tasks
(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/week/month
- [ ] component/BulletJournalWeek
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General

## Value Proposition
- Why do you say "weekend" here, but it's a weekly log? I thought it was meant for the entire week?

## Description
- If the user clicks "last" or "next", he cannot go back to the current week, can he?
- How does the user know what the current week is?

## Acceptance Criteria
- "You may modify each day by clicking on it.": Please be more precises here. Is the user navigated to the Daily Log of this day? Or, if I click on Monday, all days from Tuesday go further down below and I can see the information of Monday on the same page?
- Where do I add the "weekly objective? And when is it necessary, when is it not?
- Please add the navbar to the wireframe.

## Tasks
- You can remove Global Styles because you only set them up in the first story; after that you may adjust them, but that's not a task on its own.
