### ISSUE TITLE
Monthly Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#12]
## Value Proposition

As a User
I need a Monthly Log
to be able to work with it.

## Description

![Monthly Log](https://user-images.githubusercontent.com/106076920/179475592-3018e750-5a90-43e6-9baa-d122f05e0f3f.png)

Scribble / design or text

## Acceptance Criteria
- [ ] The heading states "Monthly."
- [ ] The list may be scrolled through.
- [ ] Each day is part of a week, but not every week is part of the same month. 
- [ ] You may modify each day by clicking on it.
- [ ] There are three boxes beneath that are buttons.
- [ ] The three buttons are labeled "last month," "next month," and "current year"

## Tasks
(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/week/month
- [ ] component/BulletJournalMonthly
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
