### ISSUE TITLE
10) All Years Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#16]
## Value Proposition

As a User
I need an "All Years" Log
to be able to get an overvie

## Description

![All Years Log](https://user-images.githubusercontent.com/106076920/179480937-674f6c74-26eb-4546-bc31-597172b9c646.png)

Scribble / design or text

## Acceptance Criteria
- [ ] The heading states "All Years."
- [ ] The list may be scrolled through.
- [ ] Each year is part of a list, but not every year is part of the same decade. 
- [ ] You may modify each day by clicking on it.
- [ ] There are three boxes beneath that are buttons.

## Tasks
(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/Year/AllYears
- [ ] component/BulletJournalAllYears
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
