### ISSUE TITLE
11)

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#17]
## Value Proposition

As a User
I need a List Log Design
to be able to write down my notes

## Description

![List Log Design](https://user-images.githubusercontent.com/106076920/179481849-5bb9d0bf-693c-4ce5-bdd2-6a2611b2b69e.png)

Scribble / design or text

## Acceptance Criteria

- [ ] Enter the task in the "Enter the Task" area.
- [ ] The "Create" button causes the job to be added to the list.
- [ ] The "Completed" column shows that the task has been finished.
- [ ] The parameter "Task open" indicates that the task is still active.
- [ ]  Each list item begins with a box; if this is checked, the task is complete. 
- [ ] 
## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials/Lists
- [ ] component/"name"-List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
