### ISSUE TITLE
12) List  Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#18]
## Value Proposition

As a User
I need a List Log 
to be able to write down my notes

## Description

![List Example Log](https://user-images.githubusercontent.com/106076920/179482604-9aca002f-cea4-4df2-876d-a8ba7384ad89.png)

Scribble / design or text

## Acceptance Criteria

- [ ] When you enter text as indicated in the functions, it appears at the bottom.
- [ ] When a job is finished, it may be marked off and shown in the Completed section.
- [ ] If the message is unchecked, it will be displayed in Task Open.
- [ ] This is the completed List Log. 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/Specials/Lists
- [ ] component/"name"-List
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
