### ISSUE TITLE
User Stories- Daily Log (My smallest Component)

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#3]
## Value Proposition

As a user
I need a daily Log
to be able to optimise my Daily Life

## Description

![Bildschirmfoto 2022-07-15 um 12 19 05](https://user-images.githubusercontent.com/106076920/179204336-a3178830-e16e-49ed-ad46-2d84ae1669b3.png)

Scribble / design or text

## Acceptance Criteria

- [ ] Daily chores can be entered
- [ ] You may then design them
- [ ] There are both open and completed tags
- [ ] The finished tags are marked with a cross
- [ ]The ones that are open are still there
- [ ] There are boxes to mark

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournalHome/BulletJournalWeek
- [ ] component/DailyLog
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Luca,

it's a good start!

💬 Let's discuss some questions I have:

- Is there a form "enter the task"? What is the submit button?
- I don't see any labels, please make clear where you want to put them.
- What does the field "completed" and "task open" do, are they part of the form?
- I would outsource the function to cross out a task into a separate user story; start by simply displaying the created task.
- Where are the boxes you mean by "There are boxes to mark"?
- What does the Date field on the upper right corner do? If nothing, outsource it to another user story.
