### ISSUE TITLE
User Stories- Weekly Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#4]
## Value Proposition

As a user
I need a Weekly Log
to be able to organize my Weekly Life

## Description

![Bildschirmfoto 2022-07-15 um 12 51 25](https://user-images.githubusercontent.com/106076920/179209462-ab8804df-9716-4111-a751-17d2d46e2b10.png)

Scribble / design or text

## Acceptance Criteria

- [ ] In the weekly log, all days of the week are linked.
- [ ] Monday through Sunday can be chosen.
- [ ] The most recent week is available.
- [ ] The next week is available.
- [ ] It is possible to choose a month. 

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournalHome/BulletJournalMonthly
- [ ] component/WeeklyLog
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App
