### ISSUE TITLE
Daily Log Functions

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#5]
## Value Proposition

As a User
I need a Daily Log
to be able to organize my day

## Description

![DailyFunction](https://user-images.githubusercontent.com/106076920/179461921-93e293da-aa6b-4bb0-9d4e-c7d1c32150f2.png)

Scribble / design or text

## Acceptance Criteria

- [ ] Enter the task in the "Enter the Task" area.
- [ ] The "Create" button causes the job to be added to the list.
- [ ] The "Completed" column shows that the task has been finished.
- [ ] The parameter "Task open" indicates that the task is still active.
- [ ]  Each list item begins with a box; if this is checked, the task is complete. 
## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalWeek
- [ ] component/DailyLog
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Luca,

looks good so far! I'd like to discuss some remarks:
- There is no label for the "Enter the task" input, where do you want to place it?
- I don't understand the "Completed" and "Task open" columns (why columns at all?):
  - Are they buttons and the user can switch between two lists?
  - If so: What happens if I check / uncheck a list item, does it switch to the other list?
- If this will be your first user story, I would suggest to outsource the checkboxes to another story.

**Comment by chris-yooo** [comment]
i don't know about that, but that's a lot of effort for the first user story.

how does it look if you first list all the tasks and create the function add a task and then in the 2nd user story think about CRUD ?

I would split it up before you cover so much in the first user story.

And before I now start to read the 2nd and 3rd I break off and wait for your feedback :)

**Comment by chris-yooo** [comment]
one more thing please post only your first user story, because i can't make 3 hooks in one post where 3 user stories are....

so in the slack 1 user story then we can also set hooks without problems :)
