### ISSUE TITLE
Daily Log

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#6]
## Value Proposition

As a User
I need a Daily Log
to be able to organize my day

## Description

![DailyLog](https://user-images.githubusercontent.com/106076920/179462015-eac81771-6e8a-4a9d-a5c5-42704e87d880.png)

Scribble / design or text

## Acceptance Criteria

- [ ] When you enter text as indicated in the functions, it appears at the bottom.
- [ ] When a job is finished, it may be marked off and shown in the Completed section.
- [ ] If the message is unchecked, it will be displayed in Task Open.
- [ ] This is the completed Daily Log. 
## Tasks

(for developers team)

- [ ] Global Styles
- [ ] connect with component/BulletJournal/BulletJournalWeek
- [ ] component/DailyLog
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with Cards
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Luca,

some questions (which may derive from the first user story as well):
- What does "as indicated in the functions" mean? I don't see any functions.
- "When a job is finished, it may be marked off and shown in the Completed section.": So there are two separated lists?
- "If the message is unchecked, it will be displayed in Task Open.": Can the user toggle the message back to "completed" as well? Please state this here.
- What do you mean by "This is the completed Daily Log." - where and why is there a not completed one?
