### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Lee1887** [Lee1887/capstone-user-stories#7]
## Value Proposition

As a user
I need a navbar
to be able to navigate myself

## Description

![Navbar](https://user-images.githubusercontent.com/106076920/179468232-1d17b169-cabf-4ea6-9ed3-aca94443739c.png)

Scribble / design or text

## Acceptance Criteria

- [ ] The fields are all navigation buttons.
- [ ] The navbar can be moved or fixed in the footer. 
- [ ] A field serves as a home button.
- [ ] One field can be used as a bullet journal button.
- [ ] One field as a Special button.
- [ ] One field as Extras button.

## Tasks
(for developers team)
- [ ] Global Styles
- [ ] connect with all components
- [ ] component/navbar
- [ ] Storybook
- [ ] Write tests
- [ ] Create db.js with button
- [ ] Add to App
